### PR TITLE
Support for OpenTelemetry 0.22

### PR DESCRIPTION
**Pull request by abdolence**

### CODE REVIEW

**Comment by lukemauldinks** [comment]
The code change looks very simple to fix the test.  When do you think this will be merged in?

**Comment by abdolence** [comment]
This was blocked by `tracing-opentelemetry` https://github.com/tokio-rs/tracing-opentelemetry/pull/100

**Comment by abdolence** [comment]
And it is still not released, so we need to wait for v0.23 release.

**Comment by lukemauldinks** [comment]
Thank you for the update, gotta love the Rust ecosystem with multiple levels of dependencies have breaking changes.

**Pull request merged**
